### ISSUE TITLE
It is recommended to strengthen the listening interface of eim.

### ISSUE THREAD

**Issue by junhuanchen** [Scratch3Lab/scratch3_eim#2]
See this building blocks.

![image](https://user-images.githubusercontent.com/32978053/53283397-cf9c9d80-3780-11e9-8f07-514b26a8af54.png)

With scratch3.codelab.club, you can't do that.

![image](https://user-images.githubusercontent.com/32978053/53283410-0e325800-3781-11e9-9565-9eb50c954171.png)

Because the listener function does not provide topic as a parameter for the user to choose.

Like I designed it

![image](https://user-images.githubusercontent.com/32978053/53283437-741edf80-3781-11e9-9c03-b402c19044ec.png)

so see this 
https://github.com/junhuanchen/webduino-module-eim/blob/f5fbfdeafaff9ca99ce51cda8df91ad637f75b85/eim-blockly.js#L19-L21
and
https://github.com/junhuanchen/webduino-module-eim/blob/f5fbfdeafaff9ca99ce51cda8df91ad637f75b85/eim.js#L35-L42

不过我发现我写的一个接口变量的调用好像有问题了（逃~）
本来这样挂多个异步回调的好处之一就是不再和其他人共用一个topic和payload的全局变量，可以通过回调参数得到各自的消息，这个在这个模型下影响不大，也可以回头再改调用的变量。

![image](https://user-images.githubusercontent.com/32978053/53283507-80576c80-3782-11e9-8e3c-1b975350b604.png)

I think TOPIC should be taken as the parameter of the listen building block(when i recvive)

or add more blocks.

**Comment by wwj718** [comment]
@junhuanchen 这是个非常有意思的讨论，关于“如何设计积木”。

就功能而言，两者应该是基本等价的，如果你认为他们在功能上有差异，我们可以就此详细讨论。

我目前看到差异主要在风格上。

EIM的基本想法是`Everything Is Message`。对于一般用户，我希望他们使用EIM的心理模型与使用scratch message积木的心理模型一样(发送一个事件消息字符串)

![image](https://user-images.githubusercontent.com/3153878/53284304-53f51d80-378d-11e9-9139-5b9c8f9b7002.png)

但EIM同时希望给高阶用户使用，帮助他们做一些临时想到的扩展功能，这部分用户可能已经学会写Python了，他们知道如何使用Python扩展scratch。此时，向他们展示scratch与adapter通信的实际message结构(topic/payload)， 但我希望他们的心理模型依然不要调整，把json本身看作普通消息即可，所以我给出字符串的格式

![image](https://user-images.githubusercontent.com/3153878/53284324-bc43ff00-378d-11e9-9136-a97166b92809.png)

箭头所连接的积木块强调对应关系

![image](https://user-images.githubusercontent.com/3153878/53284341-ded61800-378d-11e9-9d65-b883e400e81e.png)

实际上，上面的积木块是下边积木块的子集（不正交），这样做的原因是，我希望入门用户一开始不必看到payload和topic这种结构，避免增加不必要的认知负担。这种设计类似编程语言中的语法糖结构。

此外，EIM最早是在scratch3.0中实现，它不支持blockly的一些特性，所以你展示的`组合式积木`(嵌套)，目前无法在extension中直接写出。可以用自定义积木块来做（你也展示了）。

我觉得fork是很好的机制，你探索一个新的方向，我们并行去看用户的使用感受，如果社区都喜欢你的风格，我想我这边也会做相应调整。

我目前认为它是一种设计风格的差异。所以我倾向并行试错。

**Comment by wwj718** [comment]
此外 再做个补充，eim的接收消息的积木是可以解析payload的，需要使用json积木协同。我在这里有做讨论：https://blog.just4fun.site/python-scratch-with-adapter.html
