### ISSUE TITLE
Uncaught ReferenceError: content is not defined at EIMBlocks.broadcastTopicMessageAndWait 

### ISSUE THREAD

**Issue by wangshub** [Scratch3Lab/scratch3_eim#3]
https://scratch3v2.codelab.club/

![image](https://user-images.githubusercontent.com/20924010/63820439-cbde1380-c97b-11e9-8d77-995afeb2458f.png)

@wwj718

**Comment by wwj718** [comment]
![image](https://user-images.githubusercontent.com/3153878/63820760-098f6c00-c97d-11e9-9c69-b8780570a688.png)

我这儿没问题，建议更新一下插件

![image](https://user-images.githubusercontent.com/3153878/63820783-27f56780-c97d-11e9-9122-bff2db2455e8.png)

更新插件的时候，旧的插件会被备份到~/codelab_adapter打了时间戳的目录里

和刷新一下网页缓存

**Comment by wangshub** [comment]
@wwj718 

刷新网页缓存后，可以使用
