### ISSUE TITLE
How to add the green dot just like the one on the top right Conner on scratch-beta.codelab.club?

### ISSUE THREAD

**Issue by JimEverest** [Scratch3Lab/scratch3_eim#4]
Hello, I am new to Scratch and trying to implement an extension that controls an open source 4-legged robot dog in scratch.

 I installed the eim extension into my local Scratch by following this post (How to Access third-party platforms, https://adapter.codelab.club/dev_guide/接入第三方平台/), it works fine but the green dot indicates if CodeLab adapter was connected are not shown on the top-right Conner. 

Is there anyway to make it visible just like what we've seen on scratch-beta.codelab.club?

**Comment by wwj718** [comment]
Hi @JimEverest  the top-right Conner is part of scratch-gui, not part of the eim extension.

The state（color） of the top-right Conner is determined by the connectivity of the socketio， so  you can refer to [the code](https://github.com/CodeLabClub/scratch3_eim/blob/v3/codelab_adapter_base.js#L75) to implement it.

**Comment by JimEverest** [comment]
Gotcha you, thanks. oh by the way, does the adapter work with iPad?

**Comment by wwj718** [comment]
Adapter can not run on ipad ，but you can refer to:  https://adapter.codelab.club/user_guide/FAQ/#ipad
